version: "3.7"
services:
  web:
    depends_on: 
      - db
      - api
    build:
      context: ./web
      dockerfile: prod.Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
      - '/app/__sapper__'
    ports:
      - "5000:3000"

  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
      args:
        - JWT_SECRET
        - MONGODB_URI
        - PORT
        - DB_PASSWORD
        - DB_USERNAME
        - LOG_LEVEL
        - MAILGUN_API_KEY
        - MAILGUN_DOMAIN
        - API_URL
    volumes:
      - '/app/node_modules'
    depends_on:
      - db
    ports:
      - "3000:3000"

  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db

  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    working_dir: /e2e
    volumes:
      - ./web/e2e:/e2e

volumes:
  db-data:

