version: "3.7"
services:
  web:
    depends_on: 
      - db
      - api
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - "5000:3000"
      - "10000:10000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#    env_file: ./db/.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db

volumes:
  db-data:

